import{a as S,S as v,i as s}from"./assets/vendor-DuKcLXOA.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))d(t);new MutationObserver(t=>{for(const a of t)if(a.type==="childList")for(const u of a.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&d(u)}).observe(document,{childList:!0,subtree:!0});function r(t){const a={};return t.integrity&&(a.integrity=t.integrity),t.referrerPolicy&&(a.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?a.credentials="include":t.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function d(t){if(t.ep)return;t.ep=!0;const a=r(t);fetch(t.href,a)}})();const q="56318160-8874d10fff9d5cc9a89c98525",E="https://pixabay.com/api/";async function m(o,e){const r={key:q,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:15};return(await S.get(E,{params:r})).data}const h=document.querySelector(".gallery"),c=document.querySelector(".loader-container"),l=document.querySelector(".load-more-btn"),P=new v(".gallery a",{captionsData:"alt",captionDelay:250});function y(o){const e=o.map(r=>`
    <li class="gallery-item">
      <a href="${r.largeImageURL}">
        <img src="${r.webformatURL}" alt="${r.tags}" />
      </a>
      <div class="info">
        <p><b>Likes:</b> ${r.likes}</p>
        <p><b>Views:</b> ${r.views}</p>
        <p><b>Comments:</b> ${r.comments}</p>
        <p><b>Downloads:</b> ${r.downloads}</p>
      </div>
    </li>
  `).join("");h.insertAdjacentHTML("beforeend",e),P.refresh()}function B(){h.innerHTML=""}function g(){c&&c.classList.remove("hidden")}function L(){c&&c.classList.add("hidden")}function b(){l&&l.classList.remove("hidden")}function f(){l&&l.classList.add("hidden")}const p=document.querySelector(".form"),M=document.querySelector(".load-more-btn");let n="",i=1;const w=15;p.addEventListener("submit",async o=>{if(o.preventDefault(),n=o.target.elements.searchQuery.value.trim(),i=1,!n){s.error({title:"Error",message:"Please fill in the field!"});return}B(),f(),g();try{const e=await m(n,i);if(e.hits.length===0){s.warning({position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"});return}y(e.hits),e.totalHits>w&&b()}catch{s.error({position:"topRight",message:"Something went wrong, please try again later."})}finally{L(),p.reset()}});M.addEventListener("click",async()=>{i+=1,f(),g();try{const o=await m(n,i);y(o.hits),R();const e=Math.ceil(o.totalHits/w);i>=e?(f(),s.info({position:"topRight",message:"We're sorry, but you've reached the end of search results."})):b()}catch{s.error({position:"topRight",message:"Failed to load more images."})}finally{L()}});function R(){const o=document.querySelector(".gallery-item");if(o){const{height:e}=o.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
