import{a as v,S,i as a}from"./assets/vendor-DuKcLXOA.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))d(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const u of s.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&d(u)}).observe(document,{childList:!0,subtree:!0});function r(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function d(t){if(t.ep)return;t.ep=!0;const s=r(t);fetch(t.href,s)}})();const q="56318160-8874d10fff9d5cc9a89c98525",E="https://pixabay.com/api/";async function h(o,e){const r={key:q,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:15};return(await v.get(E,{params:r})).data}const m=document.querySelector(".gallery"),c=document.querySelector(".loader-container"),l=document.querySelector(".load-more-btn"),P=new S(".gallery a",{captionsData:"alt",captionDelay:250});function y(o){const e=o.map(r=>`
    <li class="gallery-item">
      <a href="${r.largeImageURL}">
        <img src="${r.webformatURL}" alt="${r.tags}" />
      </a>
      <div class="info">
        <p><b>Likes:</b> ${r.likes}</p>
        <p><b>Views:</b> ${r.views}</p>
        <p><b>Comments:</b> ${r.comments}</p>
        <p><b>Downloads:</b> ${r.downloads}</p>
      </div>
    </li>
  `).join("");m.insertAdjacentHTML("beforeend",e),P.refresh()}function R(){m.innerHTML=""}function g(){c&&c.classList.remove("hidden")}function b(){c&&c.classList.add("hidden")}function L(){l&&l.classList.remove("hidden")}function f(){l&&l.classList.add("hidden")}const p=document.querySelector(".form"),B=document.querySelector(".load-more-btn");let n="",i=1;const w=15;p.addEventListener("submit",async o=>{if(o.preventDefault(),n=o.target.elements.searchQuery.value.trim(),i=1,!n){a.error({title:"Error",message:"Please fill in the field!"});return}R(),f(),g();try{const e=await h(n,i);if(e.hits.length===0){a.warning({position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"});return}y(e.hits),e.totalHits>w?L():a.info({position:"topRight",message:"We're sorry, but you've reached the end of search results."})}catch{a.error({position:"topRight",message:"Something went wrong, please try again later."})}finally{b(),p.reset()}});B.addEventListener("click",async()=>{i+=1,f(),g();try{const o=await h(n,i);y(o.hits),M();const e=Math.ceil(o.totalHits/w);i>=e?(f(),a.info({position:"topRight",message:"We're sorry, but you've reached the end of search results."})):L()}catch{a.error({position:"topRight",message:"Failed to load more images."})}finally{b()}});function M(){const o=document.querySelector(".gallery-item");if(o){const{height:e}=o.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
