import{a as S,S as v,i as s}from"./assets/vendor-DuKcLXOA.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))f(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const d of r.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&f(d)}).observe(document,{childList:!0,subtree:!0});function a(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function f(t){if(t.ep)return;t.ep=!0;const r=a(t);fetch(t.href,r)}})();const q="56318160-8874d10fff9d5cc9a89c98525",E="https://pixabay.com/api/";async function m(o){const e={key:q,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page,per_page:15};return(await S.get(E,{params:e})).data}const h=document.querySelector(".gallery"),c=document.querySelector(".loader-container"),l=document.querySelector(".load-more-btn"),P=new v(".gallery a",{captionsData:"alt",captionDelay:250});function g(o){const e=o.map(a=>`
    <li class="gallery-item">
      <a href="${a.largeImageURL}">
        <img src="${a.webformatURL}" alt="${a.tags}" />
      </a>
      <div class="info">
        <p><b>Likes:</b> ${a.likes}</p>
        <p><b>Views:</b> ${a.views}</p>
        <p><b>Comments:</b> ${a.comments}</p>
        <p><b>Downloads:</b> ${a.downloads}</p>
      </div>
    </li>
  `).join("");h.insertAdjacentHTML("beforeend",e),P.refresh()}function B(){h.innerHTML=""}function y(){c&&c.classList.remove("hidden")}function L(){c&&c.classList.add("hidden")}function b(){l&&l.classList.remove("hidden")}function u(){l&&l.classList.add("hidden")}const p=document.querySelector(".form"),M=document.querySelector(".load-more-btn");let n="",i=1;const w=15;p.addEventListener("submit",async o=>{if(o.preventDefault(),n=o.target.elements.searchQuery.value.trim(),i=1,!n){s.error({title:"Error",message:"Please fill in the field!"});return}B(),u(),y();try{const e=await m(n,i);if(e.hits.length===0){s.warning({position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"});return}g(e.hits),e.totalHits>w&&b()}catch{s.error({position:"topRight",message:"Something went wrong, please try again later."})}finally{L(),p.reset()}});M.addEventListener("click",async()=>{i+=1,u(),y();try{const o=await m(n,i);g(o.hits),R();const e=Math.ceil(o.totalHits/w);i>=e?(u(),s.info({position:"topRight",message:"We're sorry, but you've reached the end of search results."})):b()}catch{s.error({position:"topRight",message:"Failed to load more images."})}finally{L()}});function R(){const o=document.querySelector(".gallery-item");if(o){const{height:e}=o.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
